### ISSUE TITLE
ERROR ITMS-90334: "Invalid Code Signature Identifier."

### ISSUE THREAD

**Issue by frogg** [sindresorhus/LaunchAtLogin-Legacy#47]
While uploading an app to iTunes Connect I receive the following error message within Xcode:

> ERROR ITMS-90334: Invalid Code Signature Identifier. The identifier "com.sindresorhus.LaunchAtLoginHelper" in your code signature for "LaunchAtLoginHelper" must match its Bundle Identifier "io.frogg.my.app"

![Screenshot 2020-08-28 at 23 55 40](https://user-images.githubusercontent.com/5204169/91618259-33151600-e98a-11ea-9284-c66d510c9d9d.png)

Any idea what's going on here?

**Comment by sindresorhus** [comment]
This should have been fixed in v3.0.1. What version are you using?

**Comment by frogg** [comment]
Thanks, that's good to know! I've been using the [Swift Package Manager branch](https://github.com/sindresorhus/LaunchAtLogin/pull/41) which does not include the mentioned fix so far I assume. I have now merged the latest version of your repo into that branch locally and will give it another try!

**Comment by sindresorhus** [comment]
Did you manage to resolve the issue?

**Comment by frogg** [comment]
> Did you manage to resolve the issue?

Unfortunately, not. Even with the latest commits merged into the Swift Packet Manager Branch, the problem still exists for me.

**Comment by sindresorhus** [comment]
Then it might be a separate problem with that PR.

// @SergeyKuryanov

**Comment by sindresorhus** [comment]
I'm successfully using v4 in a shipping App Store app and I did not encounter this problem.

**Comment by frogg** [comment]
Unfortunately, I still get this error when I attempt to upload to iTunes Connect:
![image](https://user-images.githubusercontent.com/5204169/94430118-ad0c0b00-0193-11eb-96aa-90e51dea502f.png)

**Comment by frogg** [comment]
Ok, I figured it out. After getting the code signing issue I checked the output of the script. And apparently the signing of LaunchAtLoginHelper failed, because I had two similar certificates for this TeamID stored in my keychain and it failed to pick one. I deleted the older one, and now it seems to work! Sorry for the confusing. I hope this might help someone in the future.

**Comment by wendellli99** [comment]
I am having the same error. But it does not seem that I have two similar certificates as you do. I took a look at packaging.log, and it has the following error:

[OPTIONAL] Didn't find embedded provisioning profile for <DVTFilePath:0x7fbba6b7cd40:'/var/folders/qx/skvpvf7x2f5_v5j_6hpqk5cw0000gn/T/XcodeDistPipeline.~~~lB24gf/Root/Applications/MyApp.app/Contents/Library/LoginItems/LaunchAtLoginHelper.app'>: Error Domain=NSCocoaErrorDomain Code=4 "No file at <DVTFilePath:0x7fbbb4a11640:'/var/folders/qx/skvpvf7x2f5_v5j_6hpqk5cw0000gn/T/XcodeDistPipeline.~~~lB24gf/Root/Applications/MyApp.app/Contents/Library/LoginItems/LaunchAtLoginHelper.app/Contents/embedded.provisionprofile'>" UserInfo={NSLocalizedDescription=No file at <DVTFilePath:0x7fbbb4a11640:'/var/folders/qx/skvpvf7x2f5_v5j_6hpqk5cw0000gn/T/XcodeDistPipeline.~~~lB24gf/Root/Applications/MyApp.app/Contents/Library/LoginItems/LaunchAtLoginHelper.app/Contents/embedded.provisionprofile'>}

**Comment by zddhub** [comment]
![Screen Shot 2022-08-09 at 20 47 11](https://user-images.githubusercontent.com/6077698/183650667-f5f39420-d5b6-45e0-a91b-25ba20a01640.png)

I met this issue as well, I used `v4.2.0` and Xcode `Version 13.4.1 (13F100)`.  I just have one certificates. Any thoughts?

**Comment by zddhub** [comment]
Ignore me, I had another certificate in my keychain as well.  After deleting it, it works for me as well.

**Comment by codeandclay** [comment]
@zddhub I have the same problem. I've deleted some certificates in my keychain but I'm not sure if they're the right ones. What certificates should I look for?

**Comment by zddhub** [comment]
@codeandclay , Maybe just keep on certificate in keychain list and have a try

**Comment by 342261733** [comment]
same problem

**Comment by sindresorhus** [comment]
Closing as I don't plan more work on this package. I recommend moving to https://github.com/sindresorhus/LaunchAtLogin-Modern
